<?php
/**
 * @author    JaJuMa GmbH <info@jajuma.de>
 * @copyright Copyright (c) 2020 JaJuMa GmbH <https://www.jajuma.de>. All rights reserved.
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */

/** @var $block \Jajuma\WebpImages\Block\Picture */
$customSrcTag = $block->getCustomSrcTag();
$customSrcSetTag = $block->getCustomSrcSetTag();

$originalTag = $block->getOriginalTag();

$isLazyLoadEnabled = $block->isNativeLazyLoadingEnabled();
$excludeNativeLazyloadImageAttributes = $block->getExcludeNativeLazyloadImageAttributes();
$isImageInExcludeList = preg_match_all($excludeNativeLazyloadImageAttributes, $originalTag);

if ($isLazyLoadEnabled && !$isImageInExcludeList) {
    // add loading="lazy" at the end of the img tag
    $originalTag = preg_replace('/>$/', ' loading="lazy" />', $originalTag);
}
?>
<?php if ($customSrcTag): ?>
    <picture>
        <source type="image/webp" <?= /* @noEscape */ $customSrcSetTag ? $customSrcSetTag : 'srcset' ?>="
        <?= /* @noEscape */ $block->getWebpImage() ?>">
        <source type="<?= /* @noEscape */ $block->getOriginalImageType() ?>" 
        <?= /* @noEscape */ $customSrcSetTag ? $customSrcSetTag : 'srcset' ?>="
        <?= /* @noEscape */ $block->getOriginalImage() ?>">
        <?= /* @noEscape */ $originalTag ?>
    </picture>
<?php else: ?>
    <picture>
        <source type="image/webp" srcset="<?= /* @noEscape */ $block->getWebpImage() ?>">
        <source type="<?= /* @noEscape */ $block->getOriginalImageType() ?>" 
        srcset="<?= /* @noEscape */ $block->getOriginalImage() ?>">
        <?= /* @noEscape */ $originalTag ?>
    </picture>
<?php endif; ?>

