<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
?>
<tr id="order-item-row-<?= (int) $_item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()) : ?>
            <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
                <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                <?php if (!$block->getPrintStatus()) : ?>
                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                    <dd>
                        <?php if (isset($_formatedOptionValue['full_view'])) : ?>
                            <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['a']) ?>
                        <?php else : ?>
                            <?=$block->escapeHtml($_formatedOptionValue['value'], ['a']) ?>
                        <?php endif; ?>
                    </dd>
                <?php else : ?>
                    <dd>
                        <?= /* @noEscape */ nl2br($block->escapeHtml($_option['print_value'] ?? $_option['value'])) ?>
                    </dd>
                <?php endif; ?>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>

        <?php //// Product Attachement code start ?>

        <?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $productAttachment = $objectManager->get('Prince\Productattach\Block\Attachment'); 
        $productId = $objectManager->get('Magento\Catalog\Model\Product')->getIdBySku($_item->getSku());

        ?>

        <div class="attachments" style="margin-top: 10px;">
            <?php if($productAttachment->isEnable()): ?>                                
                <?php $attachments = $productAttachment->getAttachment($productId); ?>  
                <?php if(count($attachments)){ ?>
                    <div class="label"><b>Product Artwork File</b></div>
                    <?php $isSize = $productAttachment->getConfig('productattach/general/attachmentsize'); ?>
                    <?php foreach ($attachments as $attachment) : ?>
                        <?php if ($attachment->getActive()) : ?>
                            <div class="product-attachment" style="margin-bottom: 10px;margin-top: 10px;">
                                <?php if ($attachment->getFile()) : ?>
                                    <a href="<?php /* @noEscape */ echo $productAttachment->getAttachmentUrl($attachment->getFile()); ?>" target="_blank" download="attachment">
                                        <div class="attachment-icon" style="float: left; padding-right: 10px;">
                                            <img src="<?php /* @noEscape */ echo $productAttachment->getFileIcon($attachment->getFileExt()) ?>" style="width: 50px; height:50px;"/>
                                        </div>
                                        <?php /* @noEscape */ //echo $attachment->getName(); ?>
                                    </a>
                                    <?php if ($isSize) : ?>
                                        <?php $size = '(Size: '.$productAttachment->getFileSize($attachment->getFile()).')' ?>
                                        <?php /* @noEscape */ echo __($size); ?>
                                    <?php endif; ?>
                                <?php elseif ($attachment->getUrl()) : ?>
                                    <a href="<?php /* @noEscape */ echo $attachment->getUrl(); ?>" target="_blank" download="attachment">
                                        <div class="attachment-icon" style="float: left; padding-right: 10px;">
                                            <img src="<?php /* @noEscape */ echo $productAttachment->getLinkIcon(); ?>" />
                                        </div>
                                        <?php /* @noEscape */ echo $attachment->getName(); ?>
                                    </a>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php  } ?>
            <?php endif; ?>
        </div>

        <?php /// Product attachement code end ?>



        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) : ?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?= $block->escapeHtml(__('SKU')) ?>"><?= /* @noEscape */ $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
        <?= $block->getItemPriceHtml() ?>
    </td>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <ul class="items-qty">
        <?php if ($block->getItem()->getQtyOrdered() > 0) : ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Ordered')) ?></span>
                <span class="content"><?= (int) $block->getItem()->getQtyOrdered() ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyShipped() > 0) : ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Shipped')) ?></span>
                <span class="content"><?= (int) $block->getItem()->getQtyShipped() ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyCanceled() > 0) : ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Canceled')) ?></span>
                <span class="content"><?= (int) $block->getItem()->getQtyCanceled() ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyRefunded() > 0) : ?>
            <li class="item">
                <span class="title"><?= $block->escapeHtml(__('Refunded')) ?></span>
                <span class="content"><?= (int) $block->getItem()->getQtyRefunded() ?></span>
            </li>
        <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?= $block->getItemRowTotalHtml() ?>
    </td>
</tr>
