<?php
/**
 * @author    JaJuMa GmbH <info@jajuma.de>
 * @copyright Copyright (c) 2020 JaJuMa GmbH <https://www.jajuma.de>. All rights reserved.
 * @license   http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm'
    ], function ($, confirm) {
        window.clearWebpImage = function() {
            confirm({
                title: '<?= /* @noEscape */__("Clear Image") ?>',
                content: '<?= /* @noEscape */__("Do you want to delete all generated webp images") ?>',
                actions: {
                    confirm: function(){ window.location.href = "<?= /* @noEscape */ $block->getAdminUrl() ?>"},
                    cancel: function(){ return false },
                    always: function(){ return false }
                }
            });
        }
    });
</script>

<?= $block->getButtonHtml() ?>