<?php

/**

 * Copyright © Magento, Inc. All rights reserved.

 * See COPYING.txt for license details.

 */



// @codingStandardsIgnoreFile



/** @var \Magento\Newsletter\Block\Subscribe $block */



?>

<div class="block newsletter">

    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>

    <div class="content">

        <p class="newsletter-label"><?= $block->escapeHtml(__('Sign up today for the latest news, offers and product launches, all delivered directly to your inbox!')) ?></p>

        <form class="form subscribe"

            novalidate

            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"

            method="post"

            data-mage-init='{"validation": {"errorClass": "mage-error"}}'

            id="newsletter-validate-detail">

            <div class="field newsletter">

                <label class="label" for="newsletter"><span><?= $block->escapeHtml(__('Newsletter')) ?></span></label>

                <div class="control">

                    <input name="email" type="email" id="newsletter"

                           placeholder="<?= $block->escapeHtml(__('Enter your email address to sign up...')) ?>"

                           data-mage-init='{"mage/trim-input":{}}'

                           data-validate="{required:true, 'validate-email':true}"/>

                </div>

            </div>

            <div class="actions">

                <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Join')) ?>" type="submit">

                    <span><?= $block->escapeHtml(__('Join')) ?></span>

                </button>

            </div>

        </form>

    </div>

</div>

