<?php
/**
 * Copyright © 2021 Magenest. All rights reserved.
 */

/**
 * @var \Magenest\Barclaycard\Block\Adminhtml\System\Config\Fieldset\Version $block
 */
?>

<div class="magenest-version-section">
    <h1>
        <a target="_blank" href="https://store.magenest.com/">Magenest Barclaycard ePDQ payment gateway</a>
    </h1>
    <div>
        Need support:
        <a target="_blank" href="http://servicedesk.izysync.com/servicedesk/customer/portal/57"><?= $block->escapeHtml(__('Submit a ticket')) ?></a>
        <br>
        Contact us:
        <a target="_blank" href="mailto:support@magenest.com"><?= $block->escapeHtml(__('support@magenest.com')) ?></a>
    </div>
    <div class="user-guide">
        To configure this extension, please read our <a target="_blank" href="http://www.confluence.izysync.com/display/DOC/2.+Barclaycard+ePDQ+Payment+Gateway+User+Guide">User Guide</a>
    </div>
    <div class="logger">
        For us to better diagnose your site, please download and send us this <a href="<?= $block->escapeUrl($block->getDownloadDebugUrl()) ?>">file</a> along with your support request
    </div>
    <div class="version">
        ver. <?= $block->escapeHtml($block->getVersion()) ?>
    </div>
</div>

<style>
    .magenest-version-section{
        background: #f8f8f8;
        border: 1px solid #e3e3e3;
        padding: 1.5rem;
    }
    .magenest-version-section h1{
        font-weight: bold;
    }
    .magenest-version-section .version{
        text-align: right;
    }
    .magenest-version-section a{
        color: #eb5202;
        text-decoration: none;
    }
    .magenest-version-section a:hover{
        color: #eb5202;
        text-decoration: none;
    }
</style>
