<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();?>
<?php $currentProduct = $objectManager->get('Magento\Framework\Registry')->registry('current_product');?>
<?php if($currentProduct && $currentProduct->getRollingClock()):?>
    <?php
        $blockObj= $block->getLayout()->createBlock('LR\CountdownTimer\Block\CountdownTimer');
        $deliveryTypes = $blockObj->getDeliveryCollection();
        $holidays = $objectManager->create('LR\CountdownTimer\Model\ResourceModel\CountdownTimer\Collection');
        $currentdate = strtotime(date('Y-m-d'));
        $htmlString = '';
        if (count($deliveryTypes))
        {
            if($holidays->count() > 0)
            {
                $holidays_dates = array();
                foreach ($holidays as $key => $value)
                {
                    $holiday_date[] =  strtotime($value['date']);
                    $formatted_holiday_date[] = $value['date'];
                }
            }
            else
            {
                $holiday_date[] = '';
            }
            sort($holiday_date);
            $holidayArray = json_encode($holiday_date);
            $holidayDateInFormatArray = json_encode($formatted_holiday_date);
        }
        else
        {
            // $resultarray['status'] = 'failed';
        }
    ?>

    <script type="text/javascript">
        require(['jquery', 'jquery/ui'], function($) {
            $(document).ready(function() {
                var currentDateTime = new Date();
                var timezoneDifference = currentDateTime.getTimezoneOffset();
                var fixedCloseTime = "13:00:00";
                var splitFixedCloseTime = fixedCloseTime.split(":");
                if(timezoneDifference < 0)
                {
                    var hrs = Math.floor(eval(-(timezoneDifference)) / 60);
                    var mins = eval(-(timezoneDifference)) % 60;
                    hrs = ((eval(splitFixedCloseTime[0])+hrs) < 10) ? "0"+(eval(splitFixedCloseTime[0])+hrs) : eval(splitFixedCloseTime[0])+hrs;
                    mins = ((eval(splitFixedCloseTime[1])+mins) < 10) ? "0"+(eval(splitFixedCloseTime[1])+mins) : (eval(splitFixedCloseTime[1])+mins);
                    fixedCloseTime = hrs+":"+mins+":00";
                }
                else
                {
                    var hrs = Math.floor(eval(timezoneDifference) / 60);
                    var mins = eval(timezoneDifference) % 60;
                    hrs = ((eval(splitFixedCloseTime[0])-hrs) < 10) ? "0"+(eval(splitFixedCloseTime[0])-hrs) : eval(splitFixedCloseTime[0])-hrs;
                    mins = ((eval(splitFixedCloseTime[1])-mins) < 10) ? "0"+(eval(splitFixedCloseTime[1])-mins) : eval(splitFixedCloseTime[1])-mins;
                    fixedCloseTime = hrs+":"+mins+":00";
                }

                var currentDateTime = new Date();
                var CDT_date = (currentDateTime.getDate() < 10) ? "0"+currentDateTime.getDate() : currentDateTime.getDate();
                var CDT_month = ((currentDateTime.getMonth()+1) < 10) ? "0"+(currentDateTime.getMonth()+1) : (currentDateTime.getMonth()+1);
                var CDT_year = currentDateTime.getFullYear();
                var CDT_hour = (currentDateTime.getHours() < 10) ? "0"+currentDateTime.getHours() : currentDateTime.getHours();
                var CDT_minute = (currentDateTime.getMinutes() < 10) ? "0"+currentDateTime.getMinutes() : currentDateTime.getMinutes();
                var CDT_second = (currentDateTime.getSeconds() < 10) ? "0"+currentDateTime.getSeconds() : currentDateTime.getSeconds();
                finalCurrentTime = CDT_month+"/"+CDT_date+"/"+CDT_year+" "+CDT_hour+":"+CDT_minute+":"+CDT_second;
                finalCloseTime = CDT_month+"/"+CDT_date+"/"+CDT_year+" "+fixedCloseTime;
                // console.log(finalCurrentTime);
                // console.log(finalCloseTime);

                // console.log('');


                // var fixedCloseTime = "13:00:00";
                // var currentDateTime = new Date();
                // var currentUKDateTime = new Date().toLocaleString('en-GB', { timeZone: 'Europe/London' });
                // console.log('currentDateTime : '+currentDateTime);
                // console.log('currentUKDateTime : '+currentUKDateTime);
                // currentUKDateTimeArray = currentUKDateTime.split(',');
                // var currentUKDate = currentUKDateTimeArray[0];
                // var currentUKTime = $.trim(currentUKDateTimeArray[1]);

                // var splitUKDate = currentUKDate.split('/');
                // splitUKDate = splitUKDate[1]+'/'+splitUKDate[0]+'/'+splitUKDate[2];
                // // console.log('splitUKDate : '+splitUKDate);

                // var finalCurrentTime = splitUKDate+' '+ currentUKTime;
                // var finalCloseTime = splitUKDate+' '+fixedCloseTime;
                
                console.log('finalCurrentTime : '+finalCurrentTime);
                console.log('finalCloseTime : '+finalCloseTime);
                var diff = new Date(finalCloseTime) - new Date(finalCurrentTime);
                console.log((new Date(finalCloseTime))+' - '+(new Date(finalCurrentTime)))
                console.log(diff);
                var loadingNextDay = 0;
                if(diff <= 0)
                {
                    diff = (86400*1000)+diff;
                    finalCurrentTime = new Date(finalCurrentTime);
                    finalCurrentTime.setDate(finalCurrentTime.getDate() + 1);
                    // console.log(finalCurrentTime);
                    var loadingNextDay = 1;
                }
                var diff_time = diff/(1000);
                var diff_time_in_round = Math.round(diff_time);
                var endTime = diff_time_in_round;
                display = $('#reverse-timer');
                var deliveredBy = '';
                var days = allWeekDays();
                var skipDays = 0;

                var deliveryDaysArray = [];
                <?php foreach ($deliveryTypes as $deliveryData) { ?>
                    var deliveryDays = <?php echo $deliveryData->getShippingDays()?>;
                    deliveryDaysArray.push(deliveryDays);
                    var todayDateTime = new Date(finalCurrentTime);
                    var deliveryDate = returnFinalDeliveryDate(todayDateTime, deliveryDays, loadingNextDay);
                    var deliveryDate_getDate = deliveryDate.getDate();
                    if(deliveryDate_getDate < 10) { deliveryDate_getDate = "0"+deliveryDate_getDate; }
                    var deliveryDate_getMonth = deliveryDate.getMonth()+1;
                    if(deliveryDate_getMonth < 10) { deliveryDate_getMonth = "0"+deliveryDate_getMonth; }
                    var deliveryDate_getFullYear = deliveryDate.getFullYear();
                    deliveryDate = deliveryDate_getDate+'/'+deliveryDate_getMonth+'/'+deliveryDate_getFullYear;
                    <?php $class = strtolower(str_replace(" ", "", $deliveryData->getShippingLabel())) ?>
                    var shippingLabel = '<?php echo $deliveryData->getShippingLabel()?>';
                    deliveredBy = "<div class='deliverBox'><div class='db-box-label'>"+shippingLabel+" Service</div><div class='db-box <?php echo $class?>_box'><span class='delivery_date_title'>Dispatched By</span><span class='delivery_date'>"+deliveryDate+"</span></div></div>";
                    $("#deliveredBy").prepend(deliveredBy);
                    // $("#deliveredByNew").prepend(deliveredBy);
                <?php } ?>

                startTimer(endTime, display, finalCurrentTime, deliveryDaysArray);
            });

            var timer;
            function startTimer(duration, display, finalCurrentTime, deliveryDaysArray)
            {
                timer = duration;
                var minutes, seconds;
                setInterval(function () {
                    var hours = Math.floor((timer) / 3600);
                    var minutes = Math.floor((timer - (hours * 3600 )) / 60);
                    var seconds = Math.floor((timer - (hours * 3600) - (minutes * 60)));

                    // if(hours < "10"){ hours = "0" + hours; }
                    // if(minutes < "10"){ minutes = "0" + minutes; }
                    // if(seconds < "10"){ seconds = "0" + seconds; }

                    //display.html(hours + ' Hour(s) ' + minutes + ' Minute(s) ' + seconds + ' Second(s)');
                    $("#reverse-timer #timer-hours").html(hours);
                    $("#reverse-timer #timer-mins").html(minutes);
                    $("#reverse-timer #timer-secs").html(seconds);

                    if (--timer < 0)
                    {
                        timer = 86400;
                        // var standarDeliveryDate = $(".standard_box .delivery_date").html();
                        // standarDeliveryDate = changeDeliveryDate(standarDeliveryDate);

                        // var expressDeliveryDate = $(".express_box .delivery_date").html();
                        // expressDeliveryDate = changeDeliveryDate(expressDeliveryDate);

                        // var superExpressDeliveryDate = $(".superexpress_box .delivery_date").html();
                        // superExpressDeliveryDate = changeDeliveryDate(superExpressDeliveryDate);

                        finalCurrentTime = new Date(finalCurrentTime);
                        finalCurrentTime.setDate(finalCurrentTime.getDate() + 1);

                        var dateExpObj = new Date(finalCurrentTime);
                        // SUPER EXPRESS DELIVEVRY DATE
                        var SEDFullDate = returnFinalDeliveryDate(dateExpObj, deliveryDaysArray[0]);
                        var d = (SEDFullDate.getDate() < 10) ? "0"+SEDFullDate.getDate() : SEDFullDate.getDate();
                        var m = ((SEDFullDate.getMonth()+1) < 10) ? "0"+(SEDFullDate.getMonth()+1) : (SEDFullDate.getMonth()+1);
                        var y = SEDFullDate.getFullYear();
                        superExpressDeliveryDate = d+'/'+m+'/'+y;

                        // EXPRESS DELIVEVRY DATE
                        var EDFullDate = returnFinalDeliveryDate(dateExpObj, deliveryDaysArray[1]);
                        var d = (EDFullDate.getDate() < 10) ? "0"+EDFullDate.getDate() : EDFullDate.getDate();
                        var m = ((EDFullDate.getMonth()+1) < 10) ? "0"+(EDFullDate.getMonth()+1) : (EDFullDate.getMonth()+1);
                        var y = EDFullDate.getFullYear();
                        expressDeliveryDate = d+'/'+m+'/'+y;

                        // STANDARD DELIVEVRY DATE
                        var SDFullDate = returnFinalDeliveryDate(dateExpObj, deliveryDaysArray[2]);
                        var d = (SDFullDate.getDate() < 10) ? "0"+SDFullDate.getDate() : SDFullDate.getDate();
                        var m = ((SDFullDate.getMonth()+1) < 10) ? "0"+(SDFullDate.getMonth()+1) : (SDFullDate.getMonth()+1);
                        var y = SDFullDate.getFullYear();
                        standarDeliveryDate = d+'/'+m+'/'+y;

                        $(".standard_box .delivery_date").html(standarDeliveryDate);
                        $(".express_box .delivery_date").html(expressDeliveryDate);
                        $(".superexpress_box .delivery_date").html(superExpressDeliveryDate);
                    }
                }, 1000);
            }

            function allWeekDays()
            {
                return ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
            }

            function returnFinalDeliveryDate(dateObj, deliveryDays, loadingNextDay)
            {
                var oneDaySeconds = 86400 * 1000;
                days = allWeekDays();
                newSkipDays = 0
                // console.log(dateObj);
                curDate = new Date(dateObj);
                del_date = curDate.setDate(curDate.getDate() + deliveryDays);
                date = new Date(del_date);

                var start_date = dateObj.getTime();
                var end_date = del_date;

                // Check holiday on Start Date (if start date exist in holiday then below code will add 1 more day in the end date) - Start
                <?php foreach(json_decode($holidayArray) as $holiday) { ?>
                    var holidayDate = <?php echo $holiday ?>;
                    holidayDate = new Date(holidayDate * 1000);
                    var holidayDateInFormat = holidayDate.toISOString().slice(0,10);
                    var start_dateInFormat = dateObj.toISOString().slice(0,10);
                    var dateInFormat = date.toISOString().slice(0,10);
                    if(holidayDateInFormat==start_dateInFormat)
                    {
                        dateObj.setDate(dateObj.getDate() + 1);
                        date.setDate(date.getDate() + 1);
                        var start_date = dateObj.getTime();
                        var end_date = date.getTime();
                    }
                <?php } ?>
                // console.log(start_date);
                // console.log(end_date);
                // Check holiday on Start Date (if start date exist in holiday then above code will add 1 more day in the end date) - End

                // if(loadingNextDay)
                // {
                //     start_date = start_date+oneDaySeconds;
                //     end_date = end_date+oneDaySeconds;
                // }
                // console.log(new Date(start_date));
                // console.log(new Date(end_date));
                var addMoreDays = 0;
                var allLoopDate = [];
                // for(var i=(start_date+oneDaySeconds);i<=end_date;i=i+oneDaySeconds)
                for(var i=(start_date+oneDaySeconds);i<=end_date;i=i+oneDaySeconds)
                {
                    loopdate = new Date(i);
                    // console.log(loopdate);
                    loopdateDay = loopdate.getDay();
                    dayName = days[loopdateDay];
                    var formattedLoopDate = loopdate.toISOString().slice(0,10);
                    allLoopDate.push(loopdate);
                    // console.log(formattedLoopDate);
                    // console.log(<?php //echo $holidayDateInFormatArray?>);
                    if($.inArray(formattedLoopDate, <?php echo $holidayDateInFormatArray?>)!=-1)
                    {
                        if(dayName!='Sunday' && dayName!='Saturday')
                        {
                            addMoreDays +=1;
                            end_date = end_date+oneDaySeconds;
                        }
                    }
                    // console.log(end_date);
                    if(dayName=='Sunday' || dayName=='Saturday')
                    {
                        addMoreDays += 1;
                        end_date = end_date+oneDaySeconds;
                    }
                }
                // console.log(allLoopDate);
                // del_date = end_date + (addMoreDays*oneDaySeconds);
                date = new Date(allLoopDate[allLoopDate.length-1]);
                console.log('');
                return date;
            }

            function changeDeliveryDate(deliveryDate)
            {
                days = allWeekDays();
                newSkipDays = 0
                var splitDate = deliveryDate.split('/');
                var date = new Date(splitDate[1]+'/'+splitDate[0]+'/'+splitDate[2]);
                var newdate = new Date(date);
                newdate.setDate(newdate.getDate() + 1);
                dayNumber = newdate.getDay();
                if(days[dayNumber]=='Saturday')
                {
                    newSkipDays = 2;
                }
                if(days[dayNumber]=='Sunday')
                {
                    newSkipDays = 1;
                }
                newdate.setDate(newdate.getDate() + newSkipDays);
                // checkHolidayOnTheGivenDate(newdate);
                <?php foreach(json_decode($holidayArray) as $holiday) { ?>
                    var holidayDate1 = <?php echo $holiday ?>;
                    holidayDate1 = new Date(holidayDate1 * 1000);
                    deliveryDate1 = new Date(newdate);

                    var holidayDate1InFormat = holidayDate1.toISOString().slice(0,10);
                    var deliveryDate1_getFullYear = deliveryDate1.getFullYear();
                    var deliveryDate1_getMonth = ((deliveryDate1.getMonth()+1) < 10) ? "0"+(deliveryDate1.getMonth()+1) : (deliveryDate1.getMonth()+1);
                    var deliveryDate1_getDate = (deliveryDate1.getDate() < 10) ? "0"+deliveryDate1.getDate() : deliveryDate1.getDate();
                    var deliveryDate1INFormat = deliveryDate1_getFullYear+'-'+deliveryDate1_getMonth+'-'+deliveryDate1_getDate;
                    if(holidayDate1InFormat==deliveryDate1INFormat && days[holidayDate1.getDay()]!='Sunday' && days[holidayDate1.getDay()]!='Saturday')
                    {
                        deliveryDate1.setDate(deliveryDate1.getDate() + 1);
                        newdate = deliveryDate1;
                    }
                    if(days[newdate.getDay()]=='Saturday')
                    {
                        newdate.setDate(newdate.getDate() + 2);
                    }
                    if(days[newdate.getDay()]=='Sunday')
                    {
                        newdate.setDate(newdate.getDate() + 1);
                    }
                <?php } ?>
                newDateGetDate = (newdate.getDate() < 10) ? "0"+newdate.getDate() : newdate.getDate();
                newDateGetMonth = ((newdate.getMonth()+1) < 10) ? "0"+(newdate.getMonth()+1) : (newdate.getMonth()+1);
                deliveryDate = newDateGetDate+'/'+newDateGetMonth+'/'+newdate.getFullYear();
                console.log('');
                return deliveryDate;
            }

            // function checkHolidayOnTheGivenDate(givenDate)
            // {
            //     var givenDate_getFullYear = givenDate.getFullYear();
            //     var givenDate_getMonth = ((givenDate.getMonth()+1) < 10) ? "0"+(givenDate.getMonth()+1) : (givenDate.getMonth()+1);
            //     var givenDate_getDate = (givenDate.getDate() < 10) ? "0"+givenDate.getDate() : givenDate.getDate();
            //     var deliveryDate1INFormat = givenDate_getFullYear+'-'+givenDate_getMonth+'-'+givenDate_getDate;
            // }
        });
    </script>

    <div class="delivery_boxes">
        <div id="reverse-timer" class="need_quick_container">
            <div class="need_quick">Order Within</div>
            <div class="ticker">
                <div class="time-containter">
                    <span id="timer-hours" class="counter-cnt">0</span>
                    <span class="time-text">hours</span>
                </div>
                <div class="time-containter">
                    <span id="timer-mins" class="counter-cnt">0</span>
                    <span class="time-text">minutes</span>
                </div>
                <div class="time-containter">
                    <span id="timer-secs" class="counter-cnt">0</span>
                    <span class="time-text">seconds</span>
                </div>     
            </div>
        </div>
        <div class="delivery_boxes_items" id="deliveredBy"></div>
        <?PHP /* <div class="delivery_boxes_items" id="deliveredByNew"></div> */ ?>
    </div>
<?php endif;?>